# Generated by Django 2.0.3 on 2018-03-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='bearId',
        ),
    ]
